#!/usr/bin/env python

from gradelib import *

r = Runner()
gen = 0

name = ['mp1-part1-0', 'mp1-part1-1', 'mp1-part2-0', 'mp1-part2-1', 'mp1-part2-2']
for i in range(10):
    name.append("custom-{}".format(str(i+1)))

for s in name:
    @test(5, "thread package with public testcase {}".format(s), test_name=s)
    def test_thread_0(t):
        r.run_qemu(shell_script([t]))
        if gen == 1:
            res = r.qemu.output.split("\n")
            st = 0
            ed = 0
            while not '$ {}'.format(t) in res[st]:
                st += 1
            while not 'exited' in res[ed]:
                ed += 1
            f = open("custom_test/{}.txt".format(t), 'w')
            f.write("\n".join(res[st+1:ed+1]))
        else: 
            r.match(*(open("custom_test/{}.txt".format(t), "r").read().splitlines()))

run_tests()
